// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (session_id, note, time)
VALUES (?, ?, ?)
RETURNING id, session_id, note, time
`

type CreateEventParams struct {
	SessionID string
	Note      string
	Time      time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.SessionID, arg.Note, arg.Time)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Note,
		&i.Time,
	)
	return i, err
}

const deleteEventsBySession = `-- name: DeleteEventsBySession :exec
DELETE FROM events WHERE session_id = ?
`

func (q *Queries) DeleteEventsBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteEventsBySession, sessionID)
	return err
}

const getEventsBySession = `-- name: GetEventsBySession :many
SELECT id, session_id, note, time FROM events
WHERE session_id = ?
ORDER BY time
`

func (q *Queries) GetEventsBySession(ctx context.Context, sessionID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Note,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
