// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	ID        int64
	SessionID string
	Note      string
	Time      time.Time
}

type Probe struct {
	ID        int64
	SessionID string
	Name      string
	Position  int64
}

type Session struct {
	ID         string
	Name       string
	Date       time.Time
	StartTime  sql.NullTime
	UploadedAt time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Stage struct {
	ID        int64
	SessionID string
	Name      string
	Start     time.Time
	End       sql.NullTime
	Duration  sql.NullInt64
}

type ThermoworksDatum struct {
	ID         int64
	SessionID  string
	Timestamp  time.Time
	Probe1Temp sql.NullFloat64
	Probe2Temp sql.NullFloat64
	Probe3Temp sql.NullFloat64
	Probe4Temp sql.NullFloat64
	Probe5Temp sql.NullFloat64
	Probe6Temp sql.NullFloat64
}
