// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: probes.sql

package db

import (
	"context"
)

const createProbe = `-- name: CreateProbe :one
INSERT INTO probes (session_id, name, position)
VALUES (?, ?, ?)
RETURNING id, session_id, name, position
`

type CreateProbeParams struct {
	SessionID string
	Name      string
	Position  int64
}

func (q *Queries) CreateProbe(ctx context.Context, arg CreateProbeParams) (Probe, error) {
	row := q.db.QueryRowContext(ctx, createProbe, arg.SessionID, arg.Name, arg.Position)
	var i Probe
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const deleteProbesBySession = `-- name: DeleteProbesBySession :exec
DELETE FROM probes WHERE session_id = ?
`

func (q *Queries) DeleteProbesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteProbesBySession, sessionID)
	return err
}

const getProbesBySession = `-- name: GetProbesBySession :many
SELECT id, session_id, name, position FROM probes
WHERE session_id = ?
`

func (q *Queries) GetProbesBySession(ctx context.Context, sessionID string) ([]Probe, error) {
	rows, err := q.db.QueryContext(ctx, getProbesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Probe
	for rows.Next() {
		var i Probe
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
