// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, name, date, start_time, uploaded_at
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, name, date, start_time, uploaded_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID         string
	Name       string
	Date       time.Time
	StartTime  sql.NullTime
	UploadedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Date,
		arg.StartTime,
		arg.UploadedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, name, date, start_time, uploaded_at, created_at, updated_at FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, date, start_time, uploaded_at, created_at, updated_at FROM sessions
ORDER BY uploaded_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.StartTime,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET name = ?, date = ?, start_time = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, date, start_time, uploaded_at, created_at, updated_at
`

type UpdateSessionParams struct {
	Name      string
	Date      time.Time
	StartTime sql.NullTime
	ID        string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Name,
		arg.Date,
		arg.StartTime,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
