// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByType = `-- name: CountSessionsByType :one
SELECT COUNT(*) FROM sessions WHERE type = ?
`

func (q *Queries) CountSessionsByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, name, type, date, start_time, uploaded_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, name, date, start_time, uploaded_at, created_at, updated_at, type
`

type CreateSessionParams struct {
	ID         string
	Name       string
	Type       string
	Date       time.Time
	StartTime  sql.NullTime
	UploadedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Date,
		arg.StartTime,
		arg.UploadedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getLatestSessionID = `-- name: GetLatestSessionID :one
SELECT id FROM sessions
ORDER BY uploaded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestSessionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT id, name, date, start_time, uploaded_at, created_at, updated_at, type FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, date, start_time, uploaded_at, created_at, updated_at, type FROM sessions
ORDER BY uploaded_at DESC
LIMIT ?
OFFSET ?
`

type ListSessionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.StartTime,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByType = `-- name: ListSessionsByType :many
SELECT id, name, date, start_time, uploaded_at, created_at, updated_at, type FROM sessions
WHERE type = ?
ORDER BY uploaded_at DESC
LIMIT ?
OFFSET ?
`

type ListSessionsByTypeParams struct {
	Type   string
	Limit  int64
	Offset int64
}

func (q *Queries) ListSessionsByType(ctx context.Context, arg ListSessionsByTypeParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.StartTime,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET name = ?, type = ?, date = ?, start_time = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, date, start_time, uploaded_at, created_at, updated_at, type
`

type UpdateSessionParams struct {
	Name      string
	Type      string
	Date      time.Time
	StartTime sql.NullTime
	ID        string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Name,
		arg.Type,
		arg.Date,
		arg.StartTime,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTime,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
