// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stages.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createStage = `-- name: CreateStage :one
INSERT INTO stages (session_id, name, start, end, duration)
VALUES (?, ?, ?, ?, ?)
RETURNING id, session_id, name, start, "end", duration
`

type CreateStageParams struct {
	SessionID string
	Name      string
	Start     time.Time
	End       sql.NullTime
	Duration  sql.NullInt64
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, createStage,
		arg.SessionID,
		arg.Name,
		arg.Start,
		arg.End,
		arg.Duration,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Start,
		&i.End,
		&i.Duration,
	)
	return i, err
}

const deleteStagesBySession = `-- name: DeleteStagesBySession :exec
DELETE FROM stages WHERE session_id = ?
`

func (q *Queries) DeleteStagesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteStagesBySession, sessionID)
	return err
}

const getStagesBySession = `-- name: GetStagesBySession :many
SELECT id, session_id, name, start, "end", duration FROM stages
WHERE session_id = ?
ORDER BY start
`

func (q *Queries) GetStagesBySession(ctx context.Context, sessionID string) ([]Stage, error) {
	rows, err := q.db.QueryContext(ctx, getStagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.Start,
			&i.End,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStage = `-- name: UpdateStage :one
UPDATE stages
SET end = ?, duration = ?
WHERE id = ?
RETURNING id, session_id, name, start, "end", duration
`

type UpdateStageParams struct {
	End      sql.NullTime
	Duration sql.NullInt64
	ID       int64
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, updateStage, arg.End, arg.Duration, arg.ID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.Start,
		&i.End,
		&i.Duration,
	)
	return i, err
}
