// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thermoworks_data.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createThermoworksData = `-- name: CreateThermoworksData :one
INSERT INTO thermoworks_data (
    session_id, timestamp, probe1_temp, probe2_temp, probe3_temp, probe4_temp, probe5_temp, probe6_temp
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, session_id, timestamp, probe1_temp, probe2_temp, probe3_temp, probe4_temp, probe5_temp, probe6_temp
`

type CreateThermoworksDataParams struct {
	SessionID  string
	Timestamp  time.Time
	Probe1Temp sql.NullFloat64
	Probe2Temp sql.NullFloat64
	Probe3Temp sql.NullFloat64
	Probe4Temp sql.NullFloat64
	Probe5Temp sql.NullFloat64
	Probe6Temp sql.NullFloat64
}

func (q *Queries) CreateThermoworksData(ctx context.Context, arg CreateThermoworksDataParams) (ThermoworksDatum, error) {
	row := q.db.QueryRowContext(ctx, createThermoworksData,
		arg.SessionID,
		arg.Timestamp,
		arg.Probe1Temp,
		arg.Probe2Temp,
		arg.Probe3Temp,
		arg.Probe4Temp,
		arg.Probe5Temp,
		arg.Probe6Temp,
	)
	var i ThermoworksDatum
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Timestamp,
		&i.Probe1Temp,
		&i.Probe2Temp,
		&i.Probe3Temp,
		&i.Probe4Temp,
		&i.Probe5Temp,
		&i.Probe6Temp,
	)
	return i, err
}

const deleteThermoworksDataBySession = `-- name: DeleteThermoworksDataBySession :exec
DELETE FROM thermoworks_data WHERE session_id = ?
`

func (q *Queries) DeleteThermoworksDataBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteThermoworksDataBySession, sessionID)
	return err
}

const getThermoworksDataBySession = `-- name: GetThermoworksDataBySession :many
SELECT id, session_id, timestamp, probe1_temp, probe2_temp, probe3_temp, probe4_temp, probe5_temp, probe6_temp FROM thermoworks_data
WHERE session_id = ?
ORDER BY timestamp
`

func (q *Queries) GetThermoworksDataBySession(ctx context.Context, sessionID string) ([]ThermoworksDatum, error) {
	rows, err := q.db.QueryContext(ctx, getThermoworksDataBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThermoworksDatum
	for rows.Next() {
		var i ThermoworksDatum
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Timestamp,
			&i.Probe1Temp,
			&i.Probe2Temp,
			&i.Probe3Temp,
			&i.Probe4Temp,
			&i.Probe5Temp,
			&i.Probe6Temp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
